//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2023.02.16 at 09:07:07 AM CET
//

package de.deloma.tools.sepa.model.pain.pain0800102;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Document complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="Document">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CstmrDrctDbtInitn" type="{urn:iso:std:iso:20022:tech:xsd:pain.008.001.02}CustomerDirectDebitInitiationV02"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlRootElement(name = "Document")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Document", propOrder =
{
	"cstmrDrctDbtInitn"
})
public class Document
{

	@XmlElement(name = "CstmrDrctDbtInitn", required = true)
	protected CustomerDirectDebitInitiationV02 cstmrDrctDbtInitn;

	/**
	 * Gets the value of the cstmrDrctDbtInitn property.
	 * 
	 * @return possible object is {@link CustomerDirectDebitInitiationV02 }
	 * 
	 */
	public CustomerDirectDebitInitiationV02 getCstmrDrctDbtInitn()
	{
		return this.cstmrDrctDbtInitn;
	}

	/**
	 * Sets the value of the cstmrDrctDbtInitn property.
	 * 
	 * @param value allowed object is {@link CustomerDirectDebitInitiationV02 }
	 * 
	 */
	public void setCstmrDrctDbtInitn(final CustomerDirectDebitInitiationV02 value)
	{
		this.cstmrDrctDbtInitn = value;
	}

}
